services:
    #here all forms as services
    project.form.type.appointment:
        class: Project\Bundle\Api\Form\Type\AppointmentType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: appointment_type }
