services:
    #here all forms as services
    project.form.type.client.log:
        class: Project\Bundle\Api\Form\Type\ClientLogType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: client_log_type }
