services:
# here all repository services
#    project.repository.opportunity:
#        class: Doctrine\ORM\EntityRepository
#        factory_service: doctrine.orm.entity_manager
#        factory_method: getRepository
#        arguments:
#            - Project\Bundle\Api\Entity\Opportunity
    api.repository.client:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            -  Project\Bundle\Api\Entity\Client

    api.repository.appointment:
            class: Doctrine\ORM\EntityRepository
            factory: ['@doctrine.orm.entity_manager', getRepository]
            arguments:
                -  Project\Bundle\Api\Entity\Appointment
