project_app_dashboard:
  resource: "@ProjectAppBundle/Resources/config/routing/Dashboard.yml"

project_app_client:
  resource: "@ProjectAppBundle/Resources/config/routing/Client.yml"

project_app_appointment:
  resource: "@ProjectAppBundle/Resources/config/routing/Appointment.yml"

project_app_event:
  resource: "@ProjectAppBundle/Resources/config/routing/Event.yml"
