imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_test.yml" }
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info

oneup_flysystem:
    filesystems:
        project_cloud:
            adapter: s3_adapter
            alias:   project_filesystem

nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['https://qa-app.project.com', 'http://qa-app.project.com.s3-website-ap-southeast-1.amazonaws.com', 'http://dev-app.project.com.s3-website-ap-southeast-1.amazonaws.com']
        allow_headers: ['*']
        allow_methods: []
        expose_headers: []
        max_age: 3600
        hosts: []
        origin_regex: false