services:
# here all repository services
#    persuit.repository.opportunity:
#        class: Doctrine\ORM\EntityRepository
#        factory_service: doctrine.orm.entity_manager
#        factory_method: getRepository
#        arguments:
#            - Persuit\Bundle\Api\Entity\Opportunity
    api.repository.client:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            -  Persuit\Bundle\Api\Entity\Client
