api_client_list:
  path:     /clients
  defaults: { _controller: 'ProjectApiBundle:Client:getApiClients' }
  methods: GET

api_client:
  path:     /client/{id}
  defaults: { _controller: 'ProjectApiBundle:Client:getApiClient' }
  methods: GET
  requirements:
    id: \d+

api_client_new:
  path:   /client
  defaults: { _controller: 'ProjectApiBundle:Client:NewApiClient' }
  methods: POST

api_client_edit:
  path: /client/{id}
  defaults: { _controller: 'ProjectApiBundle:Client:UpdateApiClient' }
  methods: [PUT,PATCH]
  requirements:
    id:  \d+