app_client_list:
  path:     /clients
  defaults: { _controller: 'ProjectAppBundle:Client:getAppClients' }
  methods: GET

app_client_new:
  path: /client/new
  defaults: { _controller: 'ProjectAppBundle:Client:newAppClient' }
  methods: [GET, POST]

app_client_edit:
  path: /client/{id}
  defaults: { _controller: 'ProjectAppBundle:Client:updateAppClient' }
  methods: [GET, PUT]
  requirements:
    id:  \d+